version: '3.3'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/home/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE : admin
      ADVERTISED_HOST : localhost
      ADVERTISED_PORT : 4409
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --innodb-buffer-pool-size=1G
      - --innodb-flush-log-at-trx-commit=0
      - --innodb-log-file-size=1G
      - --max-allowed-packet=100M
    ports :
      - '4409:3306'
    expose :
      - '3306'


  # Spring Boot Application Service
  app:
    build: .
    container_name: calendarbooking-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/calendarbooking?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: qwerty
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

# Volumes to persist MySQL data
volumes:
  mysql_data:
    driver: local

# Networks for communication between services
networks:
  calendar_network:
    driver: bridge
