version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - calendarbooking_volume:/var/lib/mysql
      - ./src:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calendarbooking
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --innodb-buffer-pool-size=1G
      - --innodb-flush-log-at-trx-commit=0
      - --innodb-log-file-size=1G
      - --max-allowed-packet=100M
    ports:
      - '4409:3306'  # MySQL exposed on this port
    networks:
      - calendar_network
    expose:
      - '3306'

  app:
    build: .
    container_name: calendarbooking-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/calendarbooking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - calendar_network
    restart: unless-stopped

volumes:
  calendarbooking_volume:

networks:
  calendar_network:
    driver: bridge
